# Generated by Django 4.1.3 on 2022-12-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.CharField(default='', max_length=255, verbose_name='Подписчики'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.CharField(default='', max_length=255, verbose_name='Подписки'),
        ),
    ]
