# Generated by Django 4.1.3 on 2022-12-04 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_subscribers_user_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_to_photo', models.CharField(max_length=255, verbose_name='Фото материала')),
                ('url_to_open_3d_obj', models.CharField(max_length=255, verbose_name='Ссылка на 3d объект')),
                ('description', models.CharField(max_length=255, verbose_name='Описание материала')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
