# Generated by Django 4.1.7 on 2023-04-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_materialcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLInfoFromUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_gtin', models.CharField(max_length=200, verbose_name='user_gtin')),
                ('user_region_code', models.IntegerField(verbose_name='user_region_code')),
                ('user_n_classes', models.IntegerField(verbose_name='user_n_classes')),
            ],
        ),
    ]
