# Generated by Django 4.1.7 on 2023-04-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mlinfofromuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLStatPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number_of_cluster', models.IntegerField(verbose_name='user_number_of_cluster')),
                ('user_product_name', models.CharField(max_length=200, verbose_name='user_product_name')),
            ],
        ),
    ]
